version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/event-app
      - public-data:/event-app/public
      - tmp-data:/event-app/tmp
      - log-data:/event-app/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/event-app/public
      - tmp-data:/event-app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
